apiVersion: v1
kind: Secret
metadata:
  name: ldp-mysql-secret
type: Opaque
data:
  password: enIK
  username: enIK
---
apiVersion: v1
kind: Service
metadata:
  name: ldp-mysql
  labels:
    app: ldp-mysql-lab
spec:
  selector: # 匹配
    app: ldp
    tier: mysql
  ports:
    - name: mysql-service-port
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-stateful-set
  labels:
    app: ldp-mysql-stateful-set
spec:
  selector:
    matchLabels:
      app: ldp
      tier: mysql
  template:
    metadata:
      labels:
        app: ldp
        tier: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: ldp
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldp-mysql-secret
                  key: username
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ldp-mysql-secret
                  key: username
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: config-volume
              mountPath: /
      volumes:
        - name: config-volume
          configMap:
            name: mysql-cm
            items:
              - key: mysql.sh
                path: entrypoint.sh