apiVersion: v1
kind: ConfigMap
metadata:
  name: ldp-mysql-cm
data:
  password: "123456"
  username: "zr"
---
apiVersion: v1
kind: Service
metadata:
  name: ldp-mysql
  labels:
    app: ldp-mysql-lab
spec:
  selector: # 匹配
    app: ldp
    tier: mysql
  clusterIP: None
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stateful-set
  labels:
    app: ldp-mysql-stateful-set
spec:
  serviceName: ldp-mysql
  selector:
    matchLabels:
      app: ldp
      tier: mysql
  template:
    metadata:
      labels:
        app: ldp
        tier: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: password
                  name: ldp-mysql-cm
            - name: MYSQL_DATABASE
              value: ldp
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: username
                  name: ldp-mysql-cm
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: password
                  name: ldp-mysql-cm

          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        storageClassName: fast
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  readOnly: "false"
  path: /data/k8s
  server: 10.211.55.7

