AppName: ldp
Env: dev
GrpcPort: 8098
HttpPort: 9098
JwtSk: "dSPTIVk7d0AfjGG@ls4d*Q0Z38*59L4h"
Mysql:
  User: root
  Passwd: "123456"
  Net: "tcp"
  Addr: "127.0.0.1:3307"
  DBName: ldp
  Collation: utf8mb4_unicode_ci

